services:
  streamlit-ui:
    container_name: streamlit-ui
    build:
      context: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - offensive-docker  # Remove ollama dependency
    networks:
      - ai-hacking-net
    volumes:
      - ./streamlit:/app
      - offensive-data:/offensive
    environment:
      - KALI_SSH_HOST=offensive-docker
      - KALI_SSH_USER=root
      - KALI_SSH_PASS=root

  offensive-docker:
    container_name: offensive-docker
    build:
      context: ../offensive-docker
    stdin_open: true
    tty: true
    ports:
      - "2222:22"
      - "80:80"
      - "3128:3128"
    networks:
      - ai-hacking-net
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - offensive-data:/offensive
      - ./history:/history

volumes:
  offensive-data:
  history:

networks:
  ai-hacking-net:
    driver: bridge
